name: Build README.md and deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install exiftool
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libimage-exiftool-perl
          version: 1.0
      - name: Build CSV
        run: ./build-csv.sh
      - name: Build README.md
        run: python build-readme.py
      - name: Create output directory
        run: mkdir -p out
      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: out/index.html
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🌐</text></svg>
      - name: Copy PDFs
        run: cp publications/*.pdf out/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out
      - name: Commit README.md
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add README.md
          git commit --allow-empty -m "Update README.md"
          git push
        

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2